apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 3m
  path: ./tenants
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: runtime-info
  prune: true
  serviceAccountName: flux-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
