apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: envoy-gateway
  namespace: kube-system
spec:
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: OCIRepository
      metadata:
        name: envoy-gateway
        namespace: kube-system
      spec:
        url: oci://docker.io/envoyproxy/gateway-helm
        ref:
          semver: v1.x
        interval: 24h
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: envoy-gateway
        namespace: kube-system
      spec:
        chartRef:
          kind: OCIRepository
          name: envoy-gateway
        driftDetection:
          mode: enabled
        interval: 10m
