apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
  interval: 24h
  ref:
    semver: 0.x
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: flux-operator
  driftDetection:
    mode: enabled
  interval: 10m
