apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: default
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats-exporter
  namespace: default
spec:
  chart:
    spec:
      chart: prometheus-nats-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 2.x
  driftDetection:
    mode: enabled
  interval: 10m
  values:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "7777"
    config:
      nats:
        service: nats-headless
