apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nats
  namespace: default
spec:
  interval: 24h
  url: https://nats-io.github.io/k8s/helm/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats
  namespace: default
spec:
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats
      version: 1.x
  driftDetection:
    mode: enabled
  interval: 10m
  values:
    config:
      websocket:
        enabled: true
