apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
  dependsOn:
    - name: infra-controllers
  interval: 60m
  path: ./infra/configs/base
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: runtime-info
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
  interval: 60m
  path: ./infra/controllers/base
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: runtime-info
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m
  wait: true
