apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 6.x
  dependsOn:
    - name: minio
  driftDetection:
    mode: enabled
  interval: 10m
  timeout: 3m
  values:
    # Cache configuration
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    # Gateway configuration
    gateway:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: gateway
                  app.kubernetes.io/name: loki
              topologyKey: kubernetes.io/hostname
      replicas: 2
    # Loki configuration
    loki:
      auth_enabled: false
      limits_config:
        allow_structured_metadata: true
        otlp_config:
          resource_attributes:
            attributes_config:
              - action: index_label
                regex: ^app\.kubernetes\.io\/.*$
      schemaConfig:
        configs:
          - from: "2024-04-01"
            index:
              period: 24h
              prefix: index_
            object_store: s3
            schema: v13
            store: tsdb
      storage:
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
        type: s3
        s3:
          accessKeyId: loki
          secretAccessKey: loki123!
          endpoint: http://minio.monitoring.svc.cluster.local:9000
          insecure: true
          s3ForcePathStyle: true
    # Simple scalable configuration
    backend:
      replicas: 2
    read:
      replicas: 2
    write:
      replicas: 2
    # Testing configuration
    lokiCanary:
      enabled: false
    test:
      enabled: false
