apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
  namespace: monitoring
spec:
  interval: 24h
  url: https://charts.min.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: monitoring
spec:
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
      version: 5.x
  driftDetection:
    mode: enabled
  interval: 10m
  timeout: 3m
  values:
    buckets:
      - name: loki-admin
        policy: none
        purge: false
      - name: loki-chunks
        policy: none
        purge: false
      - name: loki-ruler
        policy: none
        purge: false
      - name: mimir-alertmanager
        policy: none
        purge: false
      - name: mimir-blocks
        policy: none
        purge: false
      - name: mimir-ruler
        policy: none
        purge: false
      - name: tempo-trace
        policy: none
        purge: false
    drivesPerNode: 1
    persistence:
      size: 10Gi
    replicas: 2
    resources:
      requests:
        memory: 128Mi
    users:
      - accessKey: loki
        secretKey: loki123!
        policy: readwrite
      - accessKey: mimir
        secretKey: mimir123!
        policy: readwrite
      - accessKey: tempo
        secretKey: tempo123!
        policy: readwrite
